"""add rule flow canvas

Revision ID: df9abf932766
Revises: b95962a3885c
Create Date: 2025-12-19 10:10:00.000000

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df9abf932766'
down_revision = '03ea244985ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_flow_canvases',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_id', models.types.StringUUID(), nullable=False),
        sa.Column('type', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('current_workflow_id', models.types.StringUUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='rule_flow_canvas_pkey')
    )
    with op.batch_alter_table('rule_flow_canvases', schema=None) as batch_op:
        batch_op.create_index('rule_flow_canvas_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canvas_id', models.types.StringUUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('canvas_id')

    with op.batch_alter_table('rule_flow_canvases', schema=None) as batch_op:
        batch_op.drop_index('rule_flow_canvas_app_id_idx')

    op.drop_table('rule_flow_canvases')
    # ### end Alembic commands ###
